Faker data generation
Aboorva1/QUIZ_APP pull request #3
Opened 2022-11-28 06:07 UTC by Aboorva1

Used faker gem to generate data 
Made some design changes
Added validation in options model so that more than 4 options cannot be added for a question 
A question can have three options as false and only one option as true

2022-12-09 13:17 UTC, iMagesh commented on app/models/option.rb
> +
why is there a line space here?

2022-12-09 13:18 UTC, iMagesh commented on app/models/question.rb
>  	belongs_to :quiz
is there an alignment problem here?

2022-12-09 13:19 UTC, iMagesh commented on app/models/quiz.rb
> +    validates :title, presence: true
why did you remove the length validation for title?

2022-12-09 13:20 UTC, iMagesh commented on app/models/user.rb
> +  has_many :user_quizzes, :dependent => :destroy
can you move all of this to one line?

2022-12-09 13:21 UTC, iMagesh commented on app/views/leader_board/index.html.erb
> +                </tr>
is this aligned correctly?

2022-12-09 13:22 UTC, iMagesh requested changes
Please respond to all the comments, let's fix it all right now and merge.

2022-12-12 03:09 UTC, Aboorva1 commented on app/models/option.rb
> +
Removed the line space

2022-12-12 03:10 UTC, Aboorva1 commented on app/models/question.rb
>  	belongs_to :quiz
It is aligned properly in code

2022-12-12 03:33 UTC, Aboorva1 commented on app/models/user.rb
> +  has_many :user_quizzes, :dependent => :destroy
Tried it but it is giving error

2022-12-12 03:33 UTC, Aboorva1 commented on app/views/leader_board/index.html.erb
> +                </tr>
Fixed the alignment

2022-12-12 10:40 UTC, iMagesh commented on app/models/user.rb
> +  has_many :user_quizzes, :dependent => :destroy
maybe it is not possible

2022-12-12 10:42 UTC, merged